# This is a basic workflow to help you get started with Actions
name: Update file cff

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  release:
    types: [published]
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: Get release tag
        id: get_release_tag
        #create variable RELEASE_TAG and push it to the $GITHUB_ENV environment
        run: echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        
      # Runs a single command using the runners shell
      - name: Run a Python script
        run: python .github/workflows/update_cff.py
      
      - name: Commit and Push changes
        run: |
            git config user.email "thomasvermes.ch@gmail.com"
            git config user.name "GitHub Action"
            # Aggiungi il file modificato al commit
            git add CITATION.cff
            # Esegui il commit con un messaggio descrittivo
            git commit -m "File CITATION.cff aggiornato automaticamente (tramite Action) con nuova versione e data di rilascio"
            # Esegui il push delle modifiche al repository
            git push origin HEAD:main
